mod harness;
mod suites;

use anyhow::Result;
use harness::{run_op, BenchConfig, OpStats};
use std::net::{SocketAddr, TcpStream};
use std::time::Duration;
use suites::Suite;

const OPS: [&str; 7] = [
    "insert_one",
    "insert_bulk_100",
    "fetch_by_id",
    "fetch_page_50",
    "join_top_50",
    "update_one",
    "delete_one",
];

struct SuiteResult {
    name: &'static str,
    stats: Vec<OpStats>,
}

fn main() -> Result<()> {
    let cfg = BenchConfig::from_env();
    let tmp = std::env::temp_dir().join("rust-db-benchmark");
    std::fs::create_dir_all(&tmp)?;

    let pg_available = postgres_reachable();
    if !pg_available {
        eprintln!(
            "warning: PostgreSQL is not reachable at 127.0.0.1:5432 — running SQLite suites only.\n\
             Start one with: docker run -d -p 5432:5432 -e POSTGRES_USER=bench \\\n\
               -e POSTGRES_PASSWORD=bench -e POSTGRES_DB=bench postgres:16"
        );
    }

    let sqlite_db = |name: &str| {
        let path = tmp.join(format!("{name}.db"));
        for suffix in ["", "-wal", "-shm"] {
            let _ = std::fs::remove_file(tmp.join(format!("{name}.db{suffix}")));
        }
        path
    };

    let mut all_suites: Vec<Box<dyn Suite>> = vec![
        Box::new(suites::rusqlite_sqlite::RusqliteSqlite::new(sqlite_db(
            "rusqlite",
        ))?),
        Box::new(suites::sqlx_sqlite::SqlxSqlite::new(sqlite_db("sqlx"))?),
        Box::new(suites::diesel_sqlite::DieselSqlite::new(sqlite_db(
            "diesel",
        ))?),
        Box::new(suites::seaorm_sqlite::SeaOrmSqlite::new(sqlite_db(
            "seaorm",
        ))?),
        Box::new(suites::duckdb_duckdb::DuckDb::new(sqlite_db("duckdb"))?),
        Box::new(suites::redb_redb::Redb::new(sqlite_db("redb"))?),
    ];
    if pg_available {
        all_suites.push(Box::new(suites::tokio_postgres_pg::TokioPostgres::new()?));
        all_suites.push(Box::new(suites::sqlx_postgres::SqlxPostgres::new()?));
        all_suites.push(Box::new(suites::diesel_postgres::DieselPostgres::new()?));
        all_suites.push(Box::new(suites::seaorm_postgres::SeaOrmPostgres::new()?));
    }

    let delete_rows = cfg.warmup + cfg.iters;
    let mut results = Vec::new();
    for suite in &mut all_suites {
        eprintln!("==> {}", suite.name());
        suite.setup(delete_rows)?;
        let stats = run_suite(suite.as_mut(), &cfg)?;
        suite.teardown()?;
        results.push(SuiteResult {
            name: suite.name(),
            stats,
        });
    }
    drop(all_suites);

    let report = render_report(&results, &cfg);
    print!("{report}");
    std::fs::write("RESULTS.md", &report)?;
    eprintln!("\nwrote RESULTS.md");
    Ok(())
}

fn run_suite(suite: &mut dyn Suite, cfg: &BenchConfig) -> Result<Vec<OpStats>> {
    let w = cfg.warmup;
    // Order matches OPS.
    let stats = vec![
        run_op(w, cfg.iters, |i| suite.insert_one(i))?,
        run_op(w.min(5), cfg.bulk_iters, |i| suite.insert_bulk(i))?,
        run_op(w, cfg.iters, |i| suite.fetch_by_id(i))?,
        run_op(w, cfg.read_iters, |_| suite.fetch_page())?,
        run_op(w, cfg.read_iters, |_| suite.join_query())?,
        run_op(w, cfg.iters, |i| suite.update_one(i))?,
        run_op(w, cfg.iters, |i| suite.delete_one(i))?,
    ];
    Ok(stats)
}

fn postgres_reachable() -> bool {
    let addr: SocketAddr = "127.0.0.1:5432".parse().unwrap();
    TcpStream::connect_timeout(&addr, Duration::from_secs(2)).is_ok()
}

fn fmt_us(us: f64) -> String {
    if us >= 10_000.0 {
        format!("{:.2} ms", us / 1000.0)
    } else {
        format!("{us:.1} µs")
    }
}

fn render_report(results: &[SuiteResult], cfg: &BenchConfig) -> String {
    let mut out = String::new();
    out.push_str("# Rust Database / ORM Benchmark Results\n\n");
    out.push_str(&format!(
        "Machine-generated by `cargo run --release`. Iterations: {} per single-row op, \
         {} bulk batches of {} rows, {} per read-page op. All timings are per-operation \
         latency on a single connection (median unless noted).\n\n",
        cfg.iters,
        cfg.bulk_iters,
        suites::BULK_SIZE,
        cfg.read_iters
    ));

    // Per-operation tables.
    for (op_idx, op) in OPS.iter().enumerate() {
        out.push_str(&format!("## {op}\n\n"));
        out.push_str("| Suite | median | mean | p95 | ops/sec |\n");
        out.push_str("|---|---:|---:|---:|---:|\n");
        let best = results
            .iter()
            .map(|r| r.stats[op_idx].median_us)
            .fold(f64::INFINITY, f64::min);
        let mut rows: Vec<&SuiteResult> = results.iter().collect();
        rows.sort_by(|a, b| {
            a.stats[op_idx]
                .median_us
                .partial_cmp(&b.stats[op_idx].median_us)
                .unwrap()
        });
        for r in rows {
            let s = &r.stats[op_idx];
            let marker = if (s.median_us - best).abs() < f64::EPSILON {
                " 🏆"
            } else {
                ""
            };
            out.push_str(&format!(
                "| {}{marker} | {} | {} | {} | {:.0} |\n",
                r.name,
                fmt_us(s.median_us),
                fmt_us(s.mean_us),
                fmt_us(s.p95_us),
                s.ops_per_sec()
            ));
        }
        out.push('\n');
    }

    // Overall ranking: geometric mean of each suite's slowdown vs. the
    // fastest suite per operation. Embedded engines (SQLite, DuckDB, redb)
    // compete in one group; comparing their in-process latencies against
    // Postgres network round-trips would be apples to oranges.
    out.push_str("## Overall ranking (geometric mean of relative latency, 1.00 = fastest)\n\n");
    let is_pg = |r: &&SuiteResult| r.name.contains("PostgreSQL");
    for engine in ["Embedded (SQLite / DuckDB / redb)", "PostgreSQL"] {
        let group: Vec<&SuiteResult> = if engine == "PostgreSQL" {
            results.iter().filter(is_pg).collect()
        } else {
            results.iter().filter(|r| !is_pg(r)).collect()
        };
        if group.is_empty() {
            continue;
        }
        out.push_str(&format!("### {engine}\n\n"));
        out.push_str("| Rank | Suite | Relative latency |\n|---|---|---:|\n");
        let mut scored: Vec<(&str, f64)> = group
            .iter()
            .map(|r| {
                let mut log_sum = 0.0;
                for op_idx in 0..OPS.len() {
                    let best = group
                        .iter()
                        .map(|g| g.stats[op_idx].median_us)
                        .fold(f64::INFINITY, f64::min);
                    log_sum += (r.stats[op_idx].median_us / best).ln();
                }
                (r.name, (log_sum / OPS.len() as f64).exp())
            })
            .collect();
        scored.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap());
        for (rank, (name, score)) in scored.iter().enumerate() {
            out.push_str(&format!("| {} | {name} | {score:.2}× |\n", rank + 1));
        }
        out.push('\n');
    }

    // Lines-of-code proxy for developer effort: how much code each suite
    // needed to implement the exact same eight operations.
    out.push_str("## Benchmark implementation size (lines of code for identical operations)\n\n");
    out.push_str("| Suite | LOC | Shared definitions |\n|---|---:|---|\n");
    let loc = |src: &str| src.lines().filter(|l| !l.trim().is_empty()).count();
    let diesel_schema = loc(include_str!("suites/diesel_schema.rs"));
    let seaorm_entities = loc(include_str!("suites/seaorm_entities.rs"));
    let rows = [
        (
            "rusqlite (raw) + SQLite",
            loc(include_str!("suites/rusqlite_sqlite.rs")),
            String::new(),
        ),
        (
            "tokio-postgres (raw) + PostgreSQL",
            loc(include_str!("suites/tokio_postgres_pg.rs")),
            String::new(),
        ),
        (
            "duckdb-rs + DuckDB",
            loc(include_str!("suites/duckdb_duckdb.rs")),
            String::new(),
        ),
        (
            "redb (embedded KV)",
            loc(include_str!("suites/redb_redb.rs")),
            String::new(),
        ),
        (
            "SQLx + SQLite",
            loc(include_str!("suites/sqlx_sqlite.rs")),
            String::new(),
        ),
        (
            "SQLx + PostgreSQL",
            loc(include_str!("suites/sqlx_postgres.rs")),
            String::new(),
        ),
        (
            "Diesel + SQLite",
            loc(include_str!("suites/diesel_sqlite.rs")),
            format!("+{diesel_schema} (schema/models)"),
        ),
        (
            "Diesel + PostgreSQL",
            loc(include_str!("suites/diesel_postgres.rs")),
            format!("+{diesel_schema} (schema/models)"),
        ),
        (
            "SeaORM + SQLite",
            loc(include_str!("suites/seaorm_sqlite.rs")),
            format!("+{seaorm_entities} (entities)"),
        ),
        (
            "SeaORM + PostgreSQL",
            loc(include_str!("suites/seaorm_postgres.rs")),
            format!("+{seaorm_entities} (entities)"),
        ),
    ];
    for (name, n, shared) in rows {
        out.push_str(&format!("| {name} | {n} | {shared} |\n"));
    }
    out.push('\n');
    out
}
